"""
Schema Comparison Script: Identifies column name and datatype inconsistencies
across TBVW_ATTENDANCE, TBVW_SALES_TRANSACTIONS, and TBVW__DAILY_REVENUE_DATA_SS
"""

# Raw metadata parsed from the user's output
# Format: (TABLE_NAME, COLUMN_NAME, DATA_TYPE, CHAR_MAX_LEN, NUM_PRECISION, NUM_SCALE)

attendance_cols = {
    "Attendence Datetime": ("TIMESTAMP_NTZ", None),
    "Attendance Date Key": ("NUMBER", "38,0"),
    "Attendance Date": ("DATE", None),
    "Sale Transaction Datetime Key": ("NUMBER", "38,0"),
    "Sale Transaction Datet": ("DATE", None),
    "Sale Company Key": ("NUMBER", "38,0"),
    "Sale Company Code ": ("TEXT", "50"),
    "Sale Company Name": ("TEXT", "200"),
    "Redemption Company Key": ("NUMBER", "38,0"),
    "Redemption Company Code ": ("TEXT", "50"),
    "Redemption Company Name": ("TEXT", "200"),
    "Department Key": ("NUMBER", "38,0"),
    "Department Code": ("TEXT", "50"),
    "Department Name": ("TEXT", "100"),
    "Product Key": ("NUMBER", "38,0"),
    "Product Code": ("TEXT", "50"),
    "Product Name ": ("TEXT", "200"),
    "Ticket Code": ("TEXT", "100"),
    "Ticket Description": ("TEXT", "250"),
    "Ticket Age": ("TEXT", "250"),
    "Ticket Tier": ("TEXT", "200"),
    "Ticket Market": ("TEXT", "200"),
    "Ticket Type": ("TEXT", "250"),
    "Ticket or Product Flag": ("TEXT", "13"),
    "Annual Pass Flag": ("TEXT", "14"),
    "Yas Park Pass": ("TEXT", "13"),
    "Product Category Code": ("TEXT", "100"),
    "Product Category Name": ("TEXT", "250"),
    "Product Sub Category Code": ("TEXT", "100"),
    "Product Sub Category Name": ("TEXT", "250"),
    "Complimentary Product Flag": ("TEXT", "13"),
    "Hopper Flag": ("TEXT", "13"),
    "Farah Staff Flag": ("TEXT", "13"),
    "OMNI Annual Pass y/n": ("TEXT", "14"),
    "OMNI Multipark y/n": ("TEXT", "20"),
    "OMNI Park Combination": ("TEXT", "200"),
    "Promotion Key": ("NUMBER", "38,0"),
    "OMNI Promotion Name": ("TEXT", "2500"),
    "OMNI Promotion Code": ("TEXT", "100"),
    "Promotion Type": ("TEXT", "500"),
    "Promotion Classification": ("TEXT", "200"),
    "Promotion DMG": ("TEXT", "100"),
    "Promotion DMG Description": ("TEXT", "250"),
    "IG Discount Code": ("TEXT", "100"),
    "IG Discount Name": ("TEXT", "2500"),
    "Promotion Flag": ("TEXT", "13"),
    "Promotion Valid From": ("TIMESTAMP_NTZ", None),
    "Promotion Valid To": ("TIMESTAMP_NTZ", None),
    "Offer Percentage": ("FLOAT", None),
    "Offer Amount": ("FLOAT", None),
    "Account AK": ("TEXT", "50"),
    "Title": ("TEXT", "100"),
    "First Name": ("TEXT", "500"),
    "Middle Name": ("TEXT", "500"),
    "Last Name": ("TEXT", "500"),
    "Customer Type": ("TEXT", "20"),
    "Country of Residence ": ("TEXT", "60"),
    "Nationality ": ("TEXT", "60"),
    "Address": ("TEXT", "250"),
    "P O Box": ("TEXT", "100"),
    "City": ("TEXT", "100"),
    "Emirate State": ("TEXT", "100"),
    "Zip Pincode": ("TEXT", "20"),
    "Date of Birth": ("TIMESTAMP_NTZ", None),
    "Email ": ("TEXT", "120"),
    "Mobile Number": ("TEXT", "200"),
    "Fax Number": ("TEXT", "20"),
    "Etihad ID": ("TEXT", "20"),
    "Gender": ("TEXT", "20"),
    "Guest Type": ("TEXT", "20"),
    "Industry": ("TEXT", "20"),
    "Language": ("TEXT", "20"),
    "Marital Status": ("TEXT", "20"),
    "Occupation": ("TEXT", "500"),
    "MDM ID": ("TEXT", "100"),
    "SCV ID": ("TEXT", "100"),
    "YAS ID": ("TEXT", "100"),
    "Status": ("TEXT", "20"),
    "B2b Partner Key": ("NUMBER", "38,0"),
    "B2B Account ID": ("TEXT", "200"),
    "CRM Account ID": ("TEXT", "200"),
    "CRM Account Name": ("TEXT", "500"),
    "CRM Account Email": ("TEXT", "200"),
    "CRM Account Phone No.": ("TEXT", "200"),
    "CRM Account DMG Code": ("TEXT", "100"),
    "CRM Account DMG Name": ("TEXT", "500"),
    "CRM Account SubDMG Code": ("TEXT", "100"),
    "CRM Account SubDMG Name": ("TEXT", "500"),
    "OMNI Account ID": ("NUMBER", "38,0"),
    "OMNI Account Name": ("TEXT", "1001"),
    "OMNI Account Email": ("TEXT", "500"),
    "OMNI Account Phone No.": ("TEXT", "500"),
    "OMNI Account Category/DMG Code": ("TEXT", "200"),
    "OMNI Account Category/DMG Name": ("TEXT", "250"),
    "TravelBox Account ID": ("TEXT", "200"),
    "TravelBox Account Name": ("TEXT", "500"),
    "TravelBox Account Email": ("TEXT", "200"),
    "TravelBox Account Phone No.": ("TEXT", "50"),
    "TravelBox Account Category/DMG Code": ("TEXT", "100"),
    "TravelBox Account Category/DMG Name": ("TEXT", "250"),
    "Yas Arena Account ID": ("TEXT", "200"),
    "Yas Arena Account Name": ("TEXT", "500"),
    "Yas Arena Account Email": ("TEXT", "200"),
    "Yas Arena Account Phone No.": ("TEXT", "50"),
    "Yas Arena Account Category/DMG Code": ("TEXT", "100"),
    "Yas Arena Account Category/DMG Name": ("TEXT", "250"),
    "Oracle Account ID": ("TEXT", "200"),
    "Parent Partner CRM Account ID": ("TEXT", "200"),
    "Parent Partner CRM Account Name": ("TEXT", "500"),
    "EH DMC Flag": ("TEXT", "13"),
    "B2b Agent Key": ("NUMBER", "38,0"),
    "Agent CRM ID": ("TEXT", "200"),
    "Agent CRM Name": ("TEXT", "500"),
    "Agent CRM Email": ("TEXT", "200"),
    "Agent CRM Phone No.": ("TEXT", "50"),
    "Agent OMNI Account ID": ("TEXT", "200"),
    "Agent OMNI Account Name": ("TEXT", "500"),
    "Agent OMNI Account Email": ("TEXT", "200"),
    "Agent OMNI Account Phone No.": ("TEXT", "50"),
    "Agent TravelBox Account ID": ("TEXT", "200"),
    "Agent TravelBox Account Name": ("TEXT", "500"),
    "Agent TravelBox Account Email": ("TEXT", "200"),
    "Agent TravelBox Account Phone No.": ("TEXT", "50"),
    "Agent Yas Arena Account ID": ("TEXT", "200"),
    "Agent Yas Arena Account Name": ("TEXT", "500"),
    "Agent Yas Arena Account Email": ("TEXT", "200"),
    "Agent Yas Arena Account Phone No.": ("TEXT", "50"),
    "Agent Oracle Account ID": ("TEXT", "200"),
    "Sale Id": ("NUMBER", "38,0"),
    "Sale Item Id": ("NUMBER", "38,0"),
    "Ticket Id": ("NUMBER", "38,0"),
    "Media Code": ("TEXT", "500"),
    "Reservation Id": ("NUMBER", "38,0"),
    "Scan Action": ("TEXT", "200"),
    "Voucher Id": ("NUMBER", "38,0"),
    "Voucher Account Id": ("NUMBER", "38,0"),
    "Gate Siteid": ("NUMBER", "38,0"),
    "Base Sale ID": ("NUMBER", "38,0"),
    "Base Ticket ID": ("NUMBER", "38,0"),
    "Base Media ID": ("NUMBER", "38,0"),
    "Base Media Code": ("TEXT", "500"),
    "Base Ticket Code": ("TEXT", "100"),
    "Market Segment Based on Segmentation Rule 1": ("TEXT", "100"),
    "Market Segment Segmentation Rule 2": ("TEXT", "100"),
    "Market Segment Group 1": ("TEXT", "100"),
    "Market Segment Group 2": ("TEXT", "100"),
    "Void Type": ("NUMBER", "38,0"),
    "Void Type Description": ("TEXT", "100"),
    "WorkStation Area": ("TEXT", "100"),
    "WorkStation Channel": ("TEXT", "100"),
    "Budget Amount": ("FLOAT", None),
    "Budget Attendance": ("FLOAT", None),
    "Forecast Attendance": ("FLOAT", None),
    "Source Name": ("TEXT", "200"),
    "EH Booking Id": ("NUMBER", "38,0"),
    "EH Booking Flow": ("TEXT", "100"),
    "EH Client Country Name": ("TEXT", "200"),
    "EH Client Region Name": ("TEXT", "200"),
    "Promotion ID": ("TEXT", "100"),
    "OMNI Account Company Name": ("TEXT", "500"),
    "OMNI Account Category DMG Recursive Name": ("TEXT", "500"),
    "Voucher DMG Category Code": ("TEXT", "200"),
    "Voucher DMG Category Name": ("TEXT", "250"),
    "Voucher Company Name": ("TEXT", "500"),
    "EH Channels": ("TEXT", "13"),
    "EH Sub Channels": ("TEXT", "50"),
    "EH Segments": ("TEXT", "50"),
    "Partner Company Account Id (OMNI)": ("TEXT", "16777216"),
    "Partner Company Account Name (OMNI)": ("TEXT", "1001"),
    "Partner Account DMG Code (OMNI)": ("TEXT", "200"),
    "Partner Account DMG Description (OMNI)": ("TEXT", "250"),
    "Base Sale Workstation ID": ("TEXT", "50"),
    "Base Sale Workstation Area": ("TEXT", "100"),
    "Base Sale Channel": ("TEXT", "100"),
    "Voucher Code": ("TEXT", "100"),
    "Voucher Name": ("TEXT", "200"),
    "Attendance_Count": ("FLOAT", None),
    "Sale Transaction Type": ("NUMBER", "38,0"),
    "Sale Transaction Type Desc": ("TEXT", "200"),
    "Country of Residence New": ("TEXT", "200"),
    "Nationality New": ("TEXT", "200"),
    "Forecast Label": ("TEXT", "20"),
    "Partner Discount Card Number": ("NUMBER", "38,0"),
    "Partner Discount Expiry Date": ("TIMESTAMP_NTZ", None),
    "Partner Discount Registration Channel": ("TEXT", "32"),
    "Card Type": ("TEXT", "50"),
    "Product Group": ("TEXT", "255"),
    "Product Channel": ("TEXT", "255"),
    "Transaction ID": ("NUMBER", "38,0"),
    "Local/Distant": ("TEXT", "25"),
    "Customer Segment": ("TEXT", "150"),
    "Miral Staff Flag": ("TEXT", "13"),
    "Miral Staff ID": ("TEXT", "500"),
    "OG Code": ("TEXT", "16777216"),
    "OG Type Name": ("TEXT", "16777216"),
    "OG Segment": ("TEXT", "16777216"),
    "OG Type": ("TEXT", "16777216"),
    "OG Promotions Group": ("TEXT", "16777216"),
    "minutes": ("FLOAT", None),
    "Order ID": ("NUMBER", "38,0"),
    "Order Item ID": ("NUMBER", "38,0"),
    "Invoice ID": ("NUMBER", "38,0"),
    "CREATED_DATETIME": ("TIMESTAMP_NTZ", None),
    "DRR_Source": ("TEXT", "50"),
    "AP ACCOUNT AK": ("NUMBER", "38,0"),
    "AP ACCOUNT ID": ("NUMBER", "38,0"),
    "AP DMG CODE": ("TEXT", "200"),
    "AP DMG DESC": ("TEXT", "250"),
    "AP EMAIL ADDRESS": ("TEXT", "500"),
    "AP FIRST NAME": ("TEXT", "500"),
    "AP Mobile Number": ("TEXT", "500"),
    "AP MYPASS ID": ("TEXT", "200"),
    "AP SURNAME": ("TEXT", "500"),
    "AP/EMP CODE": ("TEXT", "500"),
    "Is CRM Event": ("TEXT", "20"),
    "CRM Event Type": ("TEXT", "100"),
    "Workstation Description": ("TEXT", "100"),
    "Usage Workstation ID": ("NUMBER", "38,0"),
    "Usage Workstation AK": ("TEXT", "100"),
    "EH Product Stream": ("TEXT", "200"),
}

sales_cols = {
    "As of Date": ("DATE", None),
    "Ticket Sale Date Time": ("TIMESTAMP_NTZ", None),
    "Ticket Usage Date": ("TIMESTAMP_NTZ", None),
    "TICKET_PRINT_DATETIME": ("TIMESTAMP_NTZ", None),
    "Ticket Print Date Time": ("TIMESTAMP_NTZ", None),
    "Ticket Active From": ("TIMESTAMP_NTZ", None),
    "Ticket Active To": ("TIMESTAMP_NTZ", None),
    "Expiry Date": ("TIMESTAMP_NTZ", None),
    "Ticket Performance Date Time": ("TIMESTAMP_NTZ", None),
    "Transaction Date Time": ("TIMESTAMP_NTZ", None),
    "Company Name": ("TEXT", "200"),
    "Entity Name": ("TEXT", "200"),
    "Entity Code": ("TEXT", "50"),
    "Ticket Sale Facility": ("TEXT", "200"),
    "Ticket Sale Facility Code": ("TEXT", "50"),
    "Revenue Stream / GL Group Name": ("TEXT", "100"),
    "Channel / GL Account Name": ("TEXT", "100"),
    "Product Type /GL Account Name": ("TEXT", "100"),
    "Product Type /GL Account Name Old": ("TEXT", "100"),
    "GL Account Code": ("TEXT", "50"),
    "GL Account Code_OLD": ("TEXT", "50"),
    "GL Account Type Code": ("TEXT", "20"),
    "GL Account Type": ("TEXT", "100"),
    "GL Account Sub Type Code": ("TEXT", "100"),
    "GL Account Sub Type Name": ("TEXT", "100"),
    "EBITDA Flag": ("TEXT", "13"),
    "Product Code": ("TEXT", "50"),
    "Product Name ": ("TEXT", "200"),
    "Ticket Code": ("TEXT", "100"),
    "Ticket Description": ("TEXT", "250"),
    "Ticket Age": ("TEXT", "250"),
    "Ticket Tier": ("TEXT", "200"),
    "Ticket Market": ("TEXT", "200"),
    "Ticket Type": ("TEXT", "250"),
    "Ticket or Product Flag": ("TEXT", "13"),
    "Annual Pass Flag": ("TEXT", "14"),
    "Dated Ticket Flag": ("TEXT", "13"),
    "Yas Park Pass": ("TEXT", "13"),
    "Product Category Name": ("TEXT", "250"),
    "Product Sub Category Code": ("TEXT", "100"),
    "Product Sub Category Name": ("TEXT", "250"),
    "Complimentary Product Flag": ("TEXT", "100"),
    "Hopper Flag": ("TEXT", "13"),
    "Farah Staff Flag": ("TEXT", "13"),
    "OMNI Annual Pass y n": ("TEXT", "14"),
    "OMNI Multipark y n": ("TEXT", "20"),
    "OMNI Park Combination": ("TEXT", "200"),
    "IG Class - IG/EATEC": ("TEXT", "100"),
    "Sub-Group - IG/EATEC": ("TEXT", "100"),
    "Department - IG/EATEC": ("TEXT", "100"),
    "Sub-Class - IG/EATEC": ("TEXT", "150"),
    "Group/Gender - IG/EATEC": ("TEXT", "100"),
    "Colour - IG/EATEC": ("TEXT", "50"),
    "Size - IG/EATEC": ("TEXT", "20"),
    "Barcode - EATEC": ("TEXT", "38"),
    "Style/VPN - EATEC": ("TEXT", "150"),
    "Vendor - EATEC": ("TEXT", "250"),
    "Character - EATEC": ("TEXT", "250"),
    "Market Segment Based on Segmentation Rule 1": ("TEXT", "100"),
    "Market Segment Segmentation Rule 2": ("TEXT", "100"),
    "Market Segment Group 1": ("TEXT", "100"),
    "Market Segment Group 2": ("TEXT", "100"),
    "Outlet Group": ("TEXT", "200"),
    "Outlet Name": ("TEXT", "250"),
    "Outlet Code": ("TEXT", "100"),
    "Store ID": ("NUMBER", "38,0"),
    "Store Name": ("TEXT", "500"),
    "Sale ID/Check Number": ("NUMBER", "38,0"),
    "Sale Item ID": ("NUMBER", "38,0"),
    "Ticket ID": ("NUMBER", "38,0"),
    "EH BOOKING ID": ("NUMBER", "38,0"),
    "Media ID": ("NUMBER", "38,0"),
    "Media Code": ("TEXT", "16777216"),
    "Reservation ID": ("NUMBER", "38,0"),
    "Base Sale ID": ("NUMBER", "38,0"),
    "Base Ticket ID": ("NUMBER", "38,0"),
    "Base Media ID": ("NUMBER", "38,0"),
    "Base Media Code": ("TEXT", "16777216"),
    "Base Ticket Code": ("TEXT", "16777216"),
    "OMNI Promotion Name": ("TEXT", "2500"),
    "OMNI Promotion Code": ("TEXT", "100"),
    "Promotion Type": ("TEXT", "500"),
    "Promotion Classification": ("TEXT", "200"),
    "Promotion DMG": ("TEXT", "100"),
    "Promotion DMG Description": ("TEXT", "250"),
    "IG Discount Code": ("TEXT", "100"),
    "IG Discount Name": ("TEXT", "2500"),
    "Promotion Flag": ("TEXT", "13"),
    "Promotion Valid From": ("TIMESTAMP_NTZ", None),
    "Promotion Valid To": ("TIMESTAMP_NTZ", None),
    "Offer Percentage": ("FLOAT", None),
    "Offer Amount": ("FLOAT", None),
    "Account AK": ("TEXT", "50"),
    "Title": ("TEXT", "100"),
    "First Name": ("TEXT", "500"),
    "Middle Name": ("TEXT", "500"),
    "Last Name": ("TEXT", "500"),
    "Customer Type": ("TEXT", "20"),
    "Country of Residence ": ("TEXT", "200"),
    "Nationality ": ("TEXT", "500"),
    "Address": ("TEXT", "250"),
    "P O Box": ("TEXT", "100"),
    "City": ("TEXT", "100"),
    "Emirate State": ("TEXT", "100"),
    "Zip Pincode": ("TEXT", "100"),
    "Date of Birth": ("TIMESTAMP_NTZ", None),
    "Email ": ("TEXT", "500"),
    "Mobile Number": ("TEXT", "200"),
    "Fax Number": ("TEXT", "20"),
    "Etihad ID": ("TEXT", "20"),
    "Gender": ("TEXT", "20"),
    "Guest Type": ("TEXT", "20"),
    "Industry": ("TEXT", "100"),
    "Language": ("TEXT", "20"),
    "Marital Status": ("TEXT", "20"),
    "Occupation": ("TEXT", "500"),
    "MDM ID": ("TEXT", "100"),
    "SCV ID": ("TEXT", "100"),
    "YAS ID": ("TEXT", "100"),
    "Status": ("TEXT", "20"),
    "B2B Account ID": ("NUMBER", "38,0"),
    "CRM Account ID": ("TEXT", "200"),
    "CRM Account Name": ("TEXT", "1500"),
    "CRM Account Number": ("TEXT", "200"),
    "CRM Account Email": ("TEXT", "200"),
    "CRM Account Phone No.": ("TEXT", "200"),
    "CRM Account DMG Code": ("TEXT", "100"),
    "CRM Account DMG Name": ("TEXT", "500"),
    "CRM Account SubDMG Code": ("TEXT", "100"),
    "CRM Account SubDMG Name": ("TEXT", "500"),
    "Partner OMNI Account ID": ("TEXT", "16777216"),
    "OMNI Account Name": ("TEXT", "1001"),
    "OMNI Account Email": ("TEXT", "500"),
    "OMNI Account Phone No.": ("TEXT", "500"),
    "Partner OMNI Account Category DMG Code": ("TEXT", "200"),
    "OMNI Account Category DMG Name": ("TEXT", "250"),
    "OMNI Account ID": ("NUMBER", "38,5"),
    "OMNI Account Category DMG Code": ("TEXT", "200"),
    "OMNI Account Category DMG Description": ("TEXT", "250"),
    "OMNI Account Category DMG Recursive Name": ("TEXT", "500"),
    "OMNI Account Category DMG Parent": ("TEXT", "250"),
    "OMNI Account Parent Category DMG Code": ("TEXT", "100"),
    "OMNI Account Parent Category DMG Description": ("TEXT", "250"),
    "OMNI Account Parent Category DMG Recursive Name": ("TEXT", "250"),
    "TravelBox Account ID": ("TEXT", "200"),
    "TravelBox Account Name": ("TEXT", "500"),
    "TravelBox Account Email": ("TEXT", "200"),
    "TravelBox Account Phone No.": ("TEXT", "50"),
    "TravelBox Account Category DMG Code": ("TEXT", "100"),
    "TravelBox Account Category DMG Name": ("TEXT", "250"),
    "Yas Arena Account ID": ("TEXT", "200"),
    "Yas Arena Account Name": ("TEXT", "500"),
    "Yas Arena Account Email": ("TEXT", "200"),
    "Yas Arena Account Phone No.": ("TEXT", "50"),
    "Yas Arena Account Category DMG Code": ("TEXT", "100"),
    "Yas Arena Account Category DMG Name": ("TEXT", "250"),
    "Oracle Account ID": ("TEXT", "200"),
    "Parent Partner CRM Account ID": ("TEXT", "200"),
    "Parent Partner CRM Account Name": ("TEXT", "500"),
    "EH DMC Flag": ("TEXT", "13"),
    "CRM Contract Status": ("TEXT", "1000"),
    "B2B Agent Reference Number": ("TEXT", "13"),
    "Agent CRM ID": ("TEXT", "200"),
    "Agent CRM Name": ("TEXT", "500"),
    "Agent CRM Email": ("TEXT", "200"),
    "Agent CRM Phone No.": ("TEXT", "50"),
    "Agent OMNI Account ID": ("TEXT", "200"),
    "Agent OMNI Account Name": ("TEXT", "500"),
    "Agent OMNI Account Email": ("TEXT", "200"),
    "Agent OMNI Account Phone No.": ("TEXT", "50"),
    "Agent TravelBox Account ID": ("TEXT", "200"),
    "Agent TravelBox Account Name": ("TEXT", "500"),
    "Agent TravelBox Account Email": ("TEXT", "200"),
    "Agent TravelBox Account Phone No.": ("TEXT", "50"),
    "Agent Yas Arena Account ID": ("TEXT", "200"),
    "Agent Yas Arena Account Name": ("TEXT", "500"),
    "Agent Yas Arena Account Email": ("TEXT", "200"),
    "Agent Yas Arena Account Phone No.": ("TEXT", "50"),
    "Agent Oracle Account ID": ("TEXT", "200"),
    "Account Manager ID": ("TEXT", "50"),
    "Account Manager Name": ("TEXT", "200"),
    "Segment Manager ID": ("TEXT", "50"),
    "Segment Manager Name": ("TEXT", "200"),
    "BU Name": ("TEXT", "200"),
    "Account Contract Status ": ("TEXT", "1000"),
    "Employee ID": ("TEXT", "16777216"),
    "Employee Name": ("TEXT", "500"),
    "Cashier ID": ("TEXT", "16777216"),
    "Cashier Name": ("TEXT", "500"),
    "User Role": ("TEXT", "500"),
    "Tender Name": ("TEXT", "200"),
    "Tender Code": ("TEXT", "50"),
    "Transaction ID ": ("NUMBER", "38,0"),
    "Item Code SKU": ("TEXT", "50"),
    "Item Barcode": ("NUMBER", "38,0"),
    "Void Type": ("NUMBER", "38,0"),
    "Void Type Description": ("TEXT", "100"),
    "Check Status": ("TEXT", "16777216"),
    "Third Party Revenue Share %": ("TEXT", "16777216"),
    "Transaction Type": ("TEXT", "16777216"),
    "Farah Staff ID": ("TEXT", "500"),
    "Voucher ID": ("TEXT", "16777216"),
    "Voucher Account ID": ("TEXT", "16777216"),
    "Memo Text": ("TEXT", "16777216"),
    "Supervisor Overwrite ID": ("TEXT", "100"),
    "Workstation ID": ("NUMBER", "38,0"),
    "WorkStation Area": ("TEXT", "100"),
    "WorkStation Channel": ("TEXT", "100"),
    "Source Name": ("TEXT", "200"),
    "Gross Sale Amount": ("FLOAT", None),
    "Net Sale Amount": ("FLOAT", None),
    "Net Sale Amount (-Tax)": ("FLOAT", None),
    "Quantity": ("NUMBER", "38,0"),
    "Total Amount": ("FLOAT", None),
    "Unit Price before discount": ("FLOAT", None),
    "Unit Price After discount": ("FLOAT", None),
    "Discount Amount": ("FLOAT", None),
    "Tax Amount": ("FLOAT", None),
    "Discount Quantity": ("NUMBER", "38,0"),
    "Tender Amount (in AED)": ("FLOAT", None),
    "Used Flag": ("TEXT", "14"),
    "Target Type": ("TEXT", "7"),
    "Target Year": ("TEXT", "16777216"),
    "Target Month": ("TEXT", "16777216"),
    "Ticket Revenue Target": ("FLOAT", None),
    "Ticket Sold Target": ("FLOAT", None),
    "F&B Revenue Target": ("FLOAT", None),
    "Retail Revenue Target": ("FLOAT", None),
    "Other Revenue Target": ("FLOAT", None),
    "Ticket Revenue Actual": ("FLOAT", None),
    "Ticket Sold Actual": ("FLOAT", None),
    "F&B Actual": ("FLOAT", None),
    "Retail Actual": ("FLOAT", None),
    "Other Actual": ("FLOAT", None),
    "Sub Analysis Code": ("TEXT", "20"),
    "Sub Analysis Code Old": ("TEXT", "20"),
    "Sub Analysis Name": ("TEXT", "250"),
    "Sub Analysis Name Old": ("TEXT", "250"),
    "Product Ticket Type": ("TEXT", "100"),
    "Payment Date Time": ("TIMESTAMP_NTZ", None),
    "Promotion ID": ("TEXT", "100"),
    "Item/SKU Code - IG/EATEC": ("TEXT", "100"),
    "Item/SKU Description - IG/EATEC": ("TEXT", "500"),
    "Item Type - IG/EATEC": ("TEXT", "200"),
    "OMNI Account Company Name": ("TEXT", "500"),
    "Voucher Code": ("TEXT", "16777216"),
    "Voucher Name": ("TEXT", "16777216"),
    "Voucher DMG Category Code": ("TEXT", "200"),
    "Voucher DMG Category Name": ("TEXT", "250"),
    "Voucher Company Name": ("TEXT", "500"),
    "Partner Company Account Id (OMNI)": ("TEXT", "16777216"),
    "Partner Company Account Name (OMNI)": ("TEXT", "1001"),
    "Partner Account DMG Code (OMNI)": ("TEXT", "200"),
    "Partner Account DMG Description (OMNI)": ("TEXT", "250"),
    "Base Sale Workstation ID": ("TEXT", "50"),
    "Base Sale Workstation Area": ("TEXT", "100"),
    "Base Sale Channel": ("TEXT", "100"),
    "Unit Recharge": ("FLOAT", None),
    "Country of Residence New": ("TEXT", "600"),
    "Nationality New": ("TEXT", "600"),
    "Operation Type": ("NUMBER", "38,0"),
    "Sale Transaction Type": ("NUMBER", "38,0"),
    "Sale Transaction Type Desc": ("TEXT", "200"),
    "MYPASS ID(OMNI)": ("TEXT", "200"),
    "OMNI Mobile Number": ("TEXT", "500"),
    "AP ACCOUNT_ID": ("NUMBER", "38,0"),
    "AP DMG CODE": ("TEXT", "200"),
    "AP DMG DESC": ("TEXT", "250"),
    "AP ACCOUNT AK": ("NUMBER", "38,0"),
    "AP FIRST NAME": ("TEXT", "500"),
    "AP SURNAME": ("TEXT", "500"),
    "AP EMAIL ADDRESS": ("TEXT", "500"),
    "AP MYPASS ID": ("TEXT", "200"),
    "AP/EMP CODE": ("TEXT", "500"),
    "AP Mobile Number": ("TEXT", "500"),
    "EH Booking Flow": ("TEXT", "100"),
    "EH Client Country Name": ("TEXT", "200"),
    "EH Client Region Name": ("TEXT", "200"),
    "EH Channels": ("TEXT", "13"),
    "EH Sub Channels": ("TEXT", "50"),
    "EH Segments": ("TEXT", "50"),
    "WorkStation Company": ("TEXT", "50"),
    "WORKSTATION AK": ("TEXT", "16777216"),
    "Form/Ticket": ("TEXT", "6"),
    "Partner Discount Card Number": ("NUMBER", "38,0"),
    "Partner Discount Expiry Date": ("TIMESTAMP_NTZ", None),
    "Partner Discount Registration Channel": ("TEXT", "32"),
    "Discount Amount(incl VAT)": ("FLOAT", None),
    "Card Type": ("TEXT", "50"),
    "Product Group": ("TEXT", "255"),
    "Product Channel": ("TEXT", "255"),
    "Tip Amount": ("FLOAT", None),
    "Local/Distant": ("TEXT", "25"),
    "Customer Segment": ("TEXT", "150"),
    "FacePass Flag": ("TEXT", "10"),
    "Miral Staff Flag": ("TEXT", "13"),
    "Miral Staff ID": ("TEXT", "500"),
    "OG Code": ("TEXT", "16777216"),
    "OG Type Name": ("TEXT", "16777216"),
    "OG Segment": ("TEXT", "16777216"),
    "OG Type": ("TEXT", "16777216"),
    "OG Promotions Group": ("TEXT", "16777216"),
    "minutes": ("FLOAT", None),
    "Order ID": ("NUMBER", "38,0"),
    "Order Item ID": ("NUMBER", "38,0"),
    "Invoice ID": ("NUMBER", "38,0"),
    "Transaction method": ("TEXT", "16777216"),
    "CREATED_DATETIME": ("TIMESTAMP_NTZ", None),
    "DRR_Source": ("TEXT", "50"),
    "Group Voucher Name": ("TEXT", "100"),
    "Group Vocuher Price": ("TEXT", "50"),
    "Group Voucher ItemType": ("TEXT", "200"),
    "People Count": ("TEXT", "100"),
    "Is CRM Event": ("TEXT", "20"),
    "CRM Event Type": ("TEXT", "100"),
    "EH Product Stream": ("TEXT", "200"),
}

revenue_cols = {
    "As of Date": ("DATE", None),
    "Attendance Date/Time": ("TIMESTAMP_NTZ", None),
    "Ticket Sale Date/Time": ("TIMESTAMP_NTZ", None),
    "Ticket Print Date/Time": ("TIMESTAMP_NTZ", None),
    "Ticket Active From": ("TIMESTAMP_NTZ", None),
    "Ticket Active To": ("TIMESTAMP_NTZ", None),
    "Expiry Date": ("TIMESTAMP_NTZ", None),
    "Ticket Performance Date/Time": ("TIMESTAMP_NTZ", None),
    "Tender Close Date Time": ("TIMESTAMP_NTZ", None),
    "Transaction Date Time": ("TIMESTAMP_NTZ", None),
    "Company Name ": ("TEXT", "200"),
    "Entity Name": ("TEXT", "200"),
    "Entity Code": ("TEXT", "50"),
    "Ticket Sale Facility": ("TEXT", "200"),
    "Ticket Use Facility": ("TEXT", "200"),
    "Ticket Sale Facility Code": ("TEXT", "50"),
    "Ticket Use Facility Code": ("TEXT", "50"),
    "Revenue Stream": ("TEXT", "100"),
    "Channel": ("TEXT", "100"),
    "Product Type": ("TEXT", "100"),
    "Product Code": ("TEXT", "50"),
    "Product Name ": ("TEXT", "200"),
    "Ticket Code": ("TEXT", "100"),
    "Ticket Description": ("TEXT", "250"),
    "Ticket Age": ("TEXT", "250"),
    "Ticket Tier": ("TEXT", "200"),
    "Ticket Market": ("TEXT", "200"),
    "Ticket Type": ("TEXT", "250"),
    "Ticket or Product Flag": ("TEXT", "13"),
    "Annual Pass Flag": ("TEXT", "14"),
    "Dated Ticket Flag": ("TEXT", "20"),
    "Yas Park Pass": ("TEXT", "13"),
    "Product Category Code": ("TEXT", "100"),
    "Product Category Name": ("TEXT", "250"),
    "Product Sub Category Code": ("TEXT", "100"),
    "Product Sub Category Name": ("TEXT", "250"),
    "Complimentary Product Flag": ("TEXT", "13"),
    "Hopper Flag": ("TEXT", "13"),
    "Farah Staff Flag": ("TEXT", "13"),
    "OMNI Annual Pass y/n": ("TEXT", "14"),
    "OMNI Multipark y/n": ("TEXT", "20"),
    "OMNI Park Combination": ("TEXT", "200"),
    "IG Class - IG/EATEC": ("TEXT", "100"),
    "Sub-Group - IG/EATEC": ("TEXT", "100"),
    "Department - IG/EATEC": ("TEXT", "100"),
    "Sub-Class - IG/EATEC": ("TEXT", "150"),
    "Group/Gender - IG/EATEC": ("TEXT", "100"),
    "Colour - IG/EATEC": ("TEXT", "50"),
    "Size - IG/EATEC": ("TEXT", "20"),
    "Barcode - EATEC": ("TEXT", "38"),
    "Style/VPN - EATEC": ("TEXT", "150"),
    "Vendor - EATEC": ("TEXT", "250"),
    "Character - EATEC": ("TEXT", "250"),
    "Market Segment - Based on Segmentation Rule 1": ("TEXT", "100"),
    "Market Segment - Based on Segmentation Rule 2": ("TEXT", "100"),
    "Market Segment Group 1": ("TEXT", "100"),
    "Market Segment Group 2": ("TEXT", "100"),
    "Outlet Group": ("TEXT", "200"),
    "Outlet Name": ("TEXT", "250"),
    "Outlet Code": ("TEXT", "100"),
    "Sale ID": ("NUMBER", "38,0"),
    "Sale Item ID": ("NUMBER", "38,0"),
    "Ticket ID": ("NUMBER", "38,0"),
    "Media ID": ("NUMBER", "38,0"),
    "Media Code": ("TEXT", "500"),
    "Reservation ID": ("NUMBER", "38,0"),
    "Base Sale ID": ("NUMBER", "38,0"),
    "Base Ticket ID": ("NUMBER", "38,0"),
    "Base Media ID": ("NUMBER", "38,0"),
    "Base Ticket Code": ("TEXT", "100"),
    "Base Media Code": ("TEXT", "100"),
    "OMNI Promotion Name": ("TEXT", "2500"),
    "OMNI Promotion Code": ("TEXT", "100"),
    "Promotion Type": ("TEXT", "500"),
    "Promotion Classification": ("TEXT", "200"),
    "Promotion DMG": ("TEXT", "100"),
    "Promotion DMG Description": ("TEXT", "250"),
    "IG Discount Code": ("TEXT", "100"),
    "IG Discount Name": ("TEXT", "2500"),
    "Promotion Flag": ("TEXT", "13"),
    "Promotion Valid From": ("TIMESTAMP_NTZ", None),
    "Promotion Valid To": ("TIMESTAMP_NTZ", None),
    "Offer Percentage": ("FLOAT", None),
    "Offer Amount": ("FLOAT", None),
    "Account AK": ("TEXT", "50"),
    "Title": ("TEXT", "100"),
    "First Name": ("TEXT", "500"),
    "Middle Name": ("TEXT", "500"),
    "Last Name": ("TEXT", "500"),
    "Full Name": ("TEXT", "1502"),
    "Customer Type": ("TEXT", "20"),
    "Nationality ": ("TEXT", "60"),
    "Country of Residence ": ("TEXT", "60"),
    "Address": ("TEXT", "250"),
    "P O Box": ("TEXT", "100"),
    "City": ("TEXT", "100"),
    "Emirate / State": ("TEXT", "100"),
    "Zip/ Pincode": ("TEXT", "100"),
    "Date of Birth": ("TIMESTAMP_NTZ", None),
    "Email ": ("TEXT", "120"),
    "Mobile Number": ("TEXT", "200"),
    "Fax Number": ("TEXT", "20"),
    "Etihad ID": ("TEXT", "20"),
    "Gender": ("TEXT", "20"),
    "Guest Type": ("TEXT", "20"),
    "Industry": ("TEXT", "100"),
    "Language": ("TEXT", "20"),
    "Marital Status": ("TEXT", "20"),
    "Occupation": ("TEXT", "500"),
    "MDM ID": ("TEXT", "100"),
    "SCV ID": ("TEXT", "100"),
    "YAS ID": ("TEXT", "100"),
    "Status": ("TEXT", "20"),
    "B2B Account ID": ("TEXT", "200"),
    "CRM Account ID": ("TEXT", "200"),
    "CRM Account Name": ("TEXT", "500"),
    "CRM Account Email": ("TEXT", "200"),
    "CRM Account Phone No.": ("TEXT", "200"),
    "CRM Account DMG Code": ("TEXT", "100"),
    "CRM Account DMG Name": ("TEXT", "500"),
    "CRM Account SubDMG Code": ("TEXT", "100"),
    "CRM Account SubDMG Name": ("TEXT", "500"),
    "OMNI Account ID": ("NUMBER", "38,0"),
    "OMNI Account Name": ("TEXT", "1001"),
    "OMNI Account Email": ("TEXT", "500"),
    "OMNI Account Phone No.": ("TEXT", "500"),
    "OMNI Account Category/DMG Code": ("TEXT", "200"),
    "OMNI Account Category/DMG Name": ("TEXT", "250"),
    "TravelBox Account ID": ("TEXT", "200"),
    "TravelBox Account Name": ("TEXT", "500"),
    "TravelBox Account Email": ("TEXT", "200"),
    "TravelBox Account Phone No.": ("TEXT", "50"),
    "TravelBox Account Category/DMG Code": ("TEXT", "100"),
    "TravelBox Account Category/DMG Name": ("TEXT", "250"),
    "Yas Arena Account ID": ("TEXT", "200"),
    "Yas Arena Account Name": ("TEXT", "500"),
    "Yas Arena Account Email": ("TEXT", "200"),
    "Yas Arena Account Phone No.": ("TEXT", "50"),
    "Yas Arena Account Category/DMG Code": ("TEXT", "100"),
    "Yas Arena Account Category/DMG Name": ("TEXT", "250"),
    "Oracle Account ID": ("TEXT", "200"),
    "Parent Partner CRM Account ID": ("TEXT", "200"),
    "Parent Partner CRM Account Name": ("TEXT", "500"),
    "EH DMC Flag": ("TEXT", "13"),
    "B2B Agent Reference Number": ("TEXT", "200"),
    "Agent CRM ID": ("TEXT", "200"),
    "Agent CRM Name": ("TEXT", "500"),
    "Agent CRM Email": ("TEXT", "200"),
    "Agent CRM Phone No.": ("TEXT", "50"),
    "Agent OMNI Account ID": ("TEXT", "200"),
    "Agent OMNI Account Name": ("TEXT", "500"),
    "Agent OMNI Account Email": ("TEXT", "200"),
    "Agent OMNI Account Phone No.": ("TEXT", "50"),
    "Agent TravelBox Account ID": ("TEXT", "200"),
    "Agent TravelBox Account Name": ("TEXT", "500"),
    "Agent TravelBox Account Email": ("TEXT", "200"),
    "Agent TravelBox Account Phone No.": ("TEXT", "50"),
    "Agent Yas Arena Account ID": ("TEXT", "200"),
    "Agent Yas Arena Account Name": ("TEXT", "500"),
    "Agent Yas Arena Account Email": ("TEXT", "200"),
    "Agent Yas Arena Account Phone No.": ("TEXT", "50"),
    "Agent Oracle Account ID": ("TEXT", "200"),
    "Account Manager ID": ("TEXT", "50"),
    "Account Manager Name": ("TEXT", "200"),
    "Segment Manager ID": ("TEXT", "50"),
    "Segment Manager Name": ("TEXT", "200"),
    "Employee ID": ("TEXT", "100"),
    "Employee Name": ("TEXT", "500"),
    "Cashier ID": ("TEXT", "100"),
    "Cashier Name": ("TEXT", "500"),
    "User Role": ("TEXT", "500"),
    "Transaction ID ": ("NUMBER", "38,0"),
    "Check Number": ("NUMBER", "38,0"),
    "doc_sequence_value": ("TEXT", "50"),
    "Item Code / SKU": ("TEXT", "50"),
    "Item Barcode": ("NUMBER", "38,0"),
    "Void Type": ("NUMBER", "38,0"),
    "Void Type Description": ("TEXT", "100"),
    "Third Party Revenue Share %": ("FLOAT", None),
    "Transaction Type": ("TEXT", "100"),
    "Transaction Type Name": ("TEXT", "200"),
    "Farah Staff ID": ("TEXT", "100"),
    "Voucher ID": ("NUMBER", "38,0"),
    "Voucher Account ID": ("NUMBER", "38,0"),
    "Memo Text": ("TEXT", "500"),
    "Supervisor Overwrite ID": ("TEXT", "100"),
    "Supervisor Overwrite Name": ("TEXT", "500"),
    "Workstation ID": ("NUMBER", "38,0"),
    "WorkStation Area": ("TEXT", "100"),
    "Source Name": ("TEXT", "200"),
    "Actual Attendance": ("NUMBER", "18,2"),
    "Budgeted Attendance": ("FLOAT", None),
    "Forecast Attendance": ("FLOAT", None),
    "Gross Revenue": ("FLOAT", None),
    "Recognized Revenue": ("FLOAT", None),
    "Budgeted Revenue": ("FLOAT", None),
    "Forecast Revenue": ("FLOAT", None),
    "Discount Amount": ("FLOAT", None),
    "Quantity": ("FLOAT", None),
    "Unit Price Before Discount": ("FLOAT", None),
    "Unit Price After Discount": ("FLOAT", None),
    "Tax Amount": ("FLOAT", None),
    "Third Party Revenue Share Amount": ("FLOAT", None),
    "Promotion ID": ("TEXT", "100"),
    "Item/SKU Code - IG/EATEC": ("TEXT", "100"),
    "Item/SKU Description - IG/EATEC": ("TEXT", "500"),
    "Item Type - IG/EATEC": ("TEXT", "200"),
    "Menu Item ID": ("TEXT", "100"),
    "Menu Item Name": ("TEXT", "250"),
    "OMNI Account Company Name": ("TEXT", "500"),
    "OMNI Account Category DMG Recursive Name": ("TEXT", "500"),
    "Voucher DMG Category Code": ("TEXT", "200"),
    "Voucher DMG Category Name": ("TEXT", "250"),
    "Voucher Company Name": ("TEXT", "500"),
    "Tender Code": ("TEXT", "50"),
    "Tender Name": ("TEXT", "200"),
    "Tender Count": ("NUMBER", "38,0"),
    "Tender Amount": ("FLOAT", None),
    "Tender Close Date": ("TIMESTAMP_NTZ", None),
    "Partner Company Account Id (OMNI)": ("TEXT", "16777216"),
    "Partner Company Account Name (OMNI)": ("TEXT", "1001"),
    "Partner Account DMG Code (OMNI)": ("TEXT", "200"),
    "Partner Account DMG Description (OMNI)": ("TEXT", "250"),
    "Base Sale Workstation ID": ("TEXT", "50"),
    "Base Sale Workstation Area": ("TEXT", "100"),
    "Base Sale Channel": ("TEXT", "100"),
    "Voucher Code": ("TEXT", "100"),
    "Voucher Name": ("TEXT", "200"),
    "Used Flag": ("TEXT", "14"),
    "Next Year Date": ("DATE", None),
    "Promotion Type Code": ("TEXT", "100"),
    "Park": ("TEXT", "250"),
    "Site": ("TEXT", "50"),
    "Product Ticket Type": ("TEXT", "100"),
    "EH Booking Id": ("NUMBER", "38,0"),
    "EH Booking Flow": ("TEXT", "100"),
    "EH Client Country Name": ("TEXT", "200"),
    "EH Client Region Name": ("TEXT", "200"),
    "EH Channels": ("TEXT", "13"),
    "EH Sub Channels": ("TEXT", "50"),
    "EH Segments": ("TEXT", "50"),
    "Season Source Market": ("TEXT", "16777216"),
    "WORKSTATION AK": ("TEXT", "200"),
    "SALE TRANSACTION TYPE": ("NUMBER", "38,0"),
    "SALE TRANSACTION TYPE DESC": ("TEXT", "200"),
    "FORECAST_LABEL": ("TEXT", "20"),
    "CURRENT_FLAG": ("TEXT", "1"),
    "FRC_MODIFIED_DATE": ("DATE", None),
    "MAX_ENTRIES": ("FLOAT", None),
    "Partner Discount Card Number": ("NUMBER", "38,0"),
    "Partner Discount Expiry Date": ("TIMESTAMP_NTZ", None),
    "Partner Discount Registration Channel": ("TEXT", "32"),
    "Discount Amount(incl VAT)": ("FLOAT", None),
    "Card Type": ("TEXT", "50"),
    "Product Group": ("TEXT", "255"),
    "Product Channel": ("TEXT", "255"),
    "Local/Distant": ("TEXT", "25"),
    "Customer Segment": ("TEXT", "150"),
    "Miral Staff Flag": ("TEXT", "13"),
    "Miral Staff ID": ("TEXT", "500"),
    "OG Code": ("TEXT", "16777216"),
    "OG Type Name": ("TEXT", "16777216"),
    "OG Segment": ("TEXT", "16777216"),
    "OG Type": ("TEXT", "16777216"),
    "OG Promotions Group": ("TEXT", "16777216"),
    "minutes": ("FLOAT", None),
    "Order ID": ("NUMBER", "38,0"),
    "Order Item ID": ("NUMBER", "38,0"),
    "Invoice ID": ("NUMBER", "38,0"),
    "Payment Status": ("TEXT", "50"),
    "CREATED_DATETIME": ("TIMESTAMP_NTZ", None),
    "DRR_Source": ("TEXT", "50"),
    "Group Voucher Name": ("TEXT", "100"),
    "Group Vocuher Price": ("TEXT", "50"),
    "Group Voucher ItemType": ("TEXT", "200"),
    "People Count": ("TEXT", "100"),
    "PARK REGION": ("TEXT", "100"),
    "Is Weekdays AP": ("TEXT", "1"),
    "Root SaleID": ("NUMBER", "38,0"),
    "Root MediaID": ("NUMBER", "38,0"),
    "Root IdentifierCode": ("TEXT", "16777216"),
    "Root SaleItemID": ("NUMBER", "38,0"),
    "Root TicketID": ("NUMBER", "38,0"),
    "Complimentary Product Flag Description": ("TEXT", "255"),
    "FWAD - Logo": ("TEXT", "250"),
    "SWAD - Species": ("TEXT", "250"),
    "Sub-Category - IG/EATEC": ("TEXT", "250"),
    "Item Character/Logo/Species": ("TEXT", "250"),
    "EH Client/Partner Name": ("TEXT", "200"),
    "EH Hotel Name": ("TEXT", "200"),
    "Is Yas Plaza Sales": ("TEXT", "20"),
    "Is CRM Event": ("TEXT", "20"),
    "CRM Event Type": ("TEXT", "100"),
    "EH Product Stream": ("TEXT", "200"),
    "Root Sale Channel": ("TEXT", "255"),
    "Is Web Face Tag": ("TEXT", "255"),
    "Category Group - IG/EATEC": ("TEXT", "255"),
}

# Now let's do the comparison
print("=" * 120)
print("SNOWFLAKE SCHEMA COMPARISON REPORT")
print("Tables: TBVW_ATTENDANCE (ATT) | TBVW_SALES_TRANSACTIONS (SAL) | TBVW__DAILY_REVENUE_DATA_SS (REV)")
print("=" * 120)

# ============================================================
# SECTION 1: TRAILING SPACES IN COLUMN NAMES
# ============================================================
print("\n")
print("=" * 120)
print("1. TRAILING/LEADING SPACES IN COLUMN NAMES")
print("=" * 120)

for table_name, cols in [("ATTENDANCE", attendance_cols), ("SALES", sales_cols), ("REVENUE", revenue_cols)]:
    for col in cols:
        if col != col.strip():
            spaces = len(col) - len(col.strip())
            where = "trailing" if col.rstrip() != col else "leading"
            print(f"  [{table_name}] '{col}' has {spaces} {where} space(s) -> should be '{col.strip()}'")

# ============================================================
# SECTION 2: NAMING INCONSISTENCIES (same concept, different names)
# ============================================================
print("\n")
print("=" * 120)
print("2. COLUMN NAMING INCONSISTENCIES ACROSS TABLES")
print("=" * 120)

# Manually identified groups of semantically same columns with different names
naming_issues = [
    {
        "concept": "Sale ID",
        "ATT": "Sale Id",
        "SAL": "Sale ID/Check Number",
        "REV": "Sale ID",
        "issue": "ATT uses 'Id' (lowercase d), SAL combines with Check Number, REV uses 'ID' (uppercase)"
    },
    {
        "concept": "Sale Item ID",
        "ATT": "Sale Item Id",
        "SAL": "Sale Item ID",
        "REV": "Sale Item ID",
        "issue": "ATT uses 'Id' (lowercase d), SAL/REV use 'ID' (uppercase)"
    },
    {
        "concept": "Ticket ID",
        "ATT": "Ticket Id",
        "SAL": "Ticket ID",
        "REV": "Ticket ID",
        "issue": "ATT uses 'Id' (lowercase d), SAL/REV use 'ID' (uppercase)"
    },
    {
        "concept": "Reservation ID",
        "ATT": "Reservation Id",
        "SAL": "Reservation ID",
        "REV": "Reservation ID",
        "issue": "ATT uses 'Id' (lowercase d), SAL/REV use 'ID' (uppercase)"
    },
    {
        "concept": "Voucher ID",
        "ATT": "Voucher Id (NUMBER)",
        "SAL": "Voucher ID (TEXT)",
        "REV": "Voucher ID (NUMBER)",
        "issue": "ATT uses 'Id' (lowercase d). Also DATATYPE mismatch: SAL=TEXT, ATT/REV=NUMBER"
    },
    {
        "concept": "Voucher Account ID",
        "ATT": "Voucher Account Id (NUMBER)",
        "SAL": "Voucher Account ID (TEXT)",
        "REV": "Voucher Account ID (NUMBER)",
        "issue": "ATT uses 'Id' (lowercase d). Also DATATYPE mismatch: SAL=TEXT, ATT/REV=NUMBER"
    },
    {
        "concept": "EH Booking ID",
        "ATT": "EH Booking Id",
        "SAL": "EH BOOKING ID",
        "REV": "EH Booking Id",
        "issue": "SAL uses ALL CAPS 'EH BOOKING ID', ATT/REV use mixed case 'EH Booking Id'"
    },
    {
        "concept": "Transaction ID",
        "ATT": "Transaction ID",
        "SAL": "Transaction ID  (trailing space)",
        "REV": "Transaction ID  (trailing space)",
        "issue": "SAL and REV have trailing space in column name"
    },
    {
        "concept": "OMNI Annual Pass y/n",
        "ATT": "OMNI Annual Pass y/n",
        "SAL": "OMNI Annual Pass y n",
        "REV": "OMNI Annual Pass y/n",
        "issue": "SAL uses 'y n' (no slash), ATT/REV use 'y/n' (with slash)"
    },
    {
        "concept": "OMNI Multipark y/n",
        "ATT": "OMNI Multipark y/n",
        "SAL": "OMNI Multipark y n",
        "REV": "OMNI Multipark y/n",
        "issue": "SAL uses 'y n' (no slash), ATT/REV use 'y/n' (with slash)"
    },
    {
        "concept": "OMNI Account Category/DMG Code",
        "ATT": "OMNI Account Category/DMG Code",
        "SAL": "OMNI Account Category DMG Code (no slash)",
        "REV": "OMNI Account Category/DMG Code",
        "issue": "SAL removes '/' between Category and DMG, ATT/REV keep it"
    },
    {
        "concept": "OMNI Account Category/DMG Name",
        "ATT": "OMNI Account Category/DMG Name",
        "SAL": "OMNI Account Category DMG Name (no slash)",
        "REV": "OMNI Account Category/DMG Name",
        "issue": "SAL removes '/' between Category and DMG, ATT/REV keep it"
    },
    {
        "concept": "TravelBox Account Category/DMG Code",
        "ATT": "TravelBox Account Category/DMG Code",
        "SAL": "TravelBox Account Category DMG Code",
        "REV": "TravelBox Account Category/DMG Code",
        "issue": "SAL removes '/', ATT/REV keep it"
    },
    {
        "concept": "TravelBox Account Category/DMG Name",
        "ATT": "TravelBox Account Category/DMG Name",
        "SAL": "TravelBox Account Category DMG Name",
        "REV": "TravelBox Account Category/DMG Name",
        "issue": "SAL removes '/', ATT/REV keep it"
    },
    {
        "concept": "Yas Arena Account Category/DMG Code",
        "ATT": "Yas Arena Account Category/DMG Code",
        "SAL": "Yas Arena Account Category DMG Code",
        "REV": "Yas Arena Account Category/DMG Code",
        "issue": "SAL removes '/', ATT/REV keep it"
    },
    {
        "concept": "Yas Arena Account Category/DMG Name",
        "ATT": "Yas Arena Account Category/DMG Name",
        "SAL": "Yas Arena Account Category DMG Name",
        "REV": "Yas Arena Account Category/DMG Name",
        "issue": "SAL removes '/', ATT/REV keep it"
    },
    {
        "concept": "Emirate/State",
        "ATT": "Emirate State",
        "SAL": "Emirate State",
        "REV": "Emirate / State",
        "issue": "REV uses 'Emirate / State' (with slash+spaces), ATT/SAL use 'Emirate State' (no separator)"
    },
    {
        "concept": "Zip/Pincode",
        "ATT": "Zip Pincode",
        "SAL": "Zip Pincode",
        "REV": "Zip/ Pincode",
        "issue": "REV uses 'Zip/ Pincode' (with slash), ATT/SAL use 'Zip Pincode' (space only)"
    },
    {
        "concept": "Company Name",
        "ATT": "Sale Company Name",
        "SAL": "Company Name",
        "REV": "Company Name  (trailing space)",
        "issue": "ATT prefixes with 'Sale'. REV has trailing space."
    },
    {
        "concept": "Market Segment Rule 1",
        "ATT": "Market Segment Based on Segmentation Rule 1",
        "SAL": "Market Segment Based on Segmentation Rule 1",
        "REV": "Market Segment - Based on Segmentation Rule 1",
        "issue": "REV adds ' - ' between 'Segment' and 'Based'"
    },
    {
        "concept": "Market Segment Rule 2",
        "ATT": "Market Segment Segmentation Rule 2",
        "SAL": "Market Segment Segmentation Rule 2",
        "REV": "Market Segment - Based on Segmentation Rule 2",
        "issue": "REV adds ' - Based on' while ATT/SAL just have 'Segmentation Rule 2'"
    },
    {
        "concept": "Sale Transaction Type",
        "ATT": "Sale Transaction Type (NUMBER)",
        "SAL": "Sale Transaction Type (NUMBER)",
        "REV": "SALE TRANSACTION TYPE (NUMBER, ALL CAPS)",
        "issue": "REV uses ALL CAPS column name"
    },
    {
        "concept": "Sale Transaction Type Desc",
        "ATT": "Sale Transaction Type Desc",
        "SAL": "Sale Transaction Type Desc",
        "REV": "SALE TRANSACTION TYPE DESC (ALL CAPS)",
        "issue": "REV uses ALL CAPS column name"
    },
    {
        "concept": "Forecast Label",
        "ATT": "Forecast Label",
        "SAL": "N/A",
        "REV": "FORECAST_LABEL (SCREAMING_SNAKE)",
        "issue": "REV uses SCREAMING_SNAKE_CASE, ATT uses Title Case"
    },
    {
        "concept": "B2B Account ID",
        "ATT": "B2B Account ID (TEXT)",
        "SAL": "B2B Account ID (NUMBER)",
        "REV": "B2B Account ID (TEXT)",
        "issue": "DATATYPE mismatch: SAL=NUMBER(38,0), ATT/REV=TEXT(200)"
    },
    {
        "concept": "AP ACCOUNT ID",
        "ATT": "AP ACCOUNT ID (NUMBER)",
        "SAL": "AP ACCOUNT_ID (NUMBER, underscore)",
        "REV": "N/A",
        "issue": "SAL uses underscore 'ACCOUNT_ID', ATT uses space 'ACCOUNT ID'"
    },
    {
        "concept": "Item Code/SKU",
        "ATT": "N/A",
        "SAL": "Item Code SKU",
        "REV": "Item Code / SKU",
        "issue": "SAL uses 'Item Code SKU' (no separator), REV uses 'Item Code / SKU' (with slash)"
    },
    {
        "concept": "Gate/Workstation Site ID",
        "ATT": "Gate Siteid",
        "SAL": "N/A",
        "REV": "N/A",
        "issue": "ATT uses inconsistent casing 'Siteid' instead of 'Site Id' or 'Site ID'"
    },
    {
        "concept": "Workstation AK",
        "ATT": "N/A",
        "SAL": "WORKSTATION AK (TEXT 16777216)",
        "REV": "WORKSTATION AK (TEXT 200)",
        "issue": "LENGTH mismatch: SAL=16777216, REV=200"
    },
    {
        "concept": "B2B Agent Reference Number",
        "ATT": "N/A",
        "SAL": "B2B Agent Reference Number (TEXT 13)",
        "REV": "B2B Agent Reference Number (TEXT 200)",
        "issue": "LENGTH mismatch: SAL=13, REV=200"
    },
    {
        "concept": "Sale Transaction Datet (Typo)",
        "ATT": "Sale Transaction Datet",
        "SAL": "N/A",
        "REV": "N/A",
        "issue": "TYPO: 'Datet' should likely be 'Date'"
    },
    {
        "concept": "Attendence Datetime (Typo)",
        "ATT": "Attendence Datetime",
        "SAL": "N/A",
        "REV": "N/A",
        "issue": "TYPO: 'Attendence' should be 'Attendance'"
    },
]

for i, item in enumerate(naming_issues, 1):
    print(f"\n  {i}. Concept: {item['concept']}")
    if item.get('ATT'): print(f"     ATT: {item['ATT']}")
    if item.get('SAL'): print(f"     SAL: {item['SAL']}")
    if item.get('REV'): print(f"     REV: {item['REV']}")
    print(f"     ISSUE: {item['issue']}")


# ============================================================
# SECTION 3: DATATYPE MISMATCHES
# ============================================================
print("\n")
print("=" * 120)
print("3. DATATYPE MISMATCHES FOR SAME-NAMED COLUMNS")
print("=" * 120)

# Compare columns that exist (after trimming) across tables
att_trimmed = {k.strip(): v for k, v in attendance_cols.items()}
sal_trimmed = {k.strip(): v for k, v in sales_cols.items()}
rev_trimmed = {k.strip(): v for k, v in revenue_cols.items()}

# Find common columns and compare
all_cols = set(att_trimmed.keys()) | set(sal_trimmed.keys()) | set(rev_trimmed.keys())

dtype_issues = []
length_issues = []

for col in sorted(all_cols):
    tables = {}
    if col in att_trimmed: tables["ATT"] = att_trimmed[col]
    if col in sal_trimmed: tables["SAL"] = sal_trimmed[col]
    if col in rev_trimmed: tables["REV"] = rev_trimmed[col]

    if len(tables) >= 2:
        types = {t: v[0] for t, v in tables.items()}
        lengths = {t: v[1] for t, v in tables.items()}

        # Check type mismatch
        unique_types = set(types.values())
        if len(unique_types) > 1:
            dtype_issues.append((col, types, lengths))

        # Check length mismatch (only for same type)
        elif len(unique_types) == 1:
            unique_lengths = set(lengths.values())
            if len(unique_lengths) > 1:
                length_issues.append((col, types, lengths))

print("\n  --- DATATYPE MISMATCHES ---")
for col, types, lengths in dtype_issues:
    type_str = " | ".join(f"{t}={v}" for t, v in types.items())
    len_str = " | ".join(f"{t}={v}" for t, v in lengths.items())
    print(f"\n  Column: '{col}'")
    print(f"    Types:   {type_str}")
    print(f"    Lengths: {len_str}")

print("\n  --- LENGTH/PRECISION MISMATCHES (same datatype) ---")
for col, types, lengths in length_issues:
    type_str = " | ".join(f"{t}={v}" for t, v in types.items())
    len_str = " | ".join(f"{t}={v}" for t, v in lengths.items())
    print(f"\n  Column: '{col}'")
    print(f"    Types:   {type_str}")
    print(f"    Lengths: {len_str}")

# ============================================================
# SECTION 4: PRODUCT CATEGORY CODE MISSING
# ============================================================
print("\n")
print("=" * 120)
print("4. COLUMNS PRESENT IN 2 TABLES BUT MISSING IN THE 3RD")
print("=" * 120)

for col in sorted(all_cols):
    in_att = col in att_trimmed
    in_sal = col in sal_trimmed
    in_rev = col in rev_trimmed

    present = []
    missing = []
    if in_att: present.append("ATT")
    else: missing.append("ATT")
    if in_sal: present.append("SAL")
    else: missing.append("SAL")
    if in_rev: present.append("REV")
    else: missing.append("REV")

    if len(present) == 2 and len(missing) == 1:
        print(f"  '{col}' -> Present in [{', '.join(present)}], MISSING in [{', '.join(missing)}]")

print("\n" + "=" * 120)
print("END OF REPORT")
print("=" * 120)
