"""initial schema

Revision ID: 0affc85f696c
Revises: 
Create Date: 2026-09-05 12:48:43.716836
"""
from alembic import op
import sqlalchemy as sa


revision = '0affc85f696c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puzzles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('fen', sa.String(length=120), nullable=False),
    sa.Column('solution_moves', sa.String(length=255), nullable=False),
    sa.Column('themes', sa.String(length=255), nullable=False),
    sa.Column('taxonomy_keys', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_puzzles_rating'), 'puzzles', ['rating'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('preferred_language', sa.String(length=32), nullable=False),
    sa.Column('current_rating_estimate', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(length=500), nullable=False),
    sa.Column('assessment_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pgn', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=True),
    sa.Column('white', sa.String(length=120), nullable=True),
    sa.Column('black', sa.String(length=120), nullable=True),
    sa.Column('user_color', sa.String(length=5), nullable=False),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_status', sa.String(length=16), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_user_id'), 'games', ['user_id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=48), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('comprehension_checks', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_topic'), 'lessons', ['topic'], unique=False)
    op.create_index(op.f('ix_lessons_user_id'), 'lessons', ['user_id'], unique=False)
    op.create_table('puzzle_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('puzzle_id', sa.String(length=32), nullable=False),
    sa.Column('weakness_key', sa.String(length=48), nullable=True),
    sa.Column('context', sa.String(length=16), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('played_move', sa.String(length=12), nullable=False),
    sa.Column('time_ms', sa.Integer(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_puzzle_attempts_puzzle_id'), 'puzzle_attempts', ['puzzle_id'], unique=False)
    op.create_index(op.f('ix_puzzle_attempts_user_id'), 'puzzle_attempts', ['user_id'], unique=False)
    op.create_table('rating_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rating_history_user_id'), 'rating_history', ['user_id'], unique=False)
    op.create_table('srs_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weakness_key', sa.String(length=48), nullable=False),
    sa.Column('ease', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Float(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('successes', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_srs_cards_due_at'), 'srs_cards', ['due_at'], unique=False)
    op.create_index(op.f('ix_srs_cards_user_id'), 'srs_cards', ['user_id'], unique=False)
    op.create_index(op.f('ix_srs_cards_weakness_key'), 'srs_cards', ['weakness_key'], unique=False)
    op.create_table('weaknesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('taxonomy_key', sa.String(length=48), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weaknesses_taxonomy_key'), 'weaknesses', ['taxonomy_key'], unique=False)
    op.create_index(op.f('ix_weaknesses_user_id'), 'weaknesses', ['user_id'], unique=False)
    op.create_table('analyzed_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('ply', sa.Integer(), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=5), nullable=False),
    sa.Column('fen', sa.String(length=120), nullable=False),
    sa.Column('played_move', sa.String(length=12), nullable=False),
    sa.Column('best_move', sa.String(length=12), nullable=False),
    sa.Column('best_line', sa.String(length=255), nullable=False),
    sa.Column('eval_cp_before', sa.Integer(), nullable=False),
    sa.Column('eval_cp_after', sa.Integer(), nullable=False),
    sa.Column('cp_loss', sa.Integer(), nullable=False),
    sa.Column('win_prob_loss', sa.Float(), nullable=False),
    sa.Column('move_label', sa.String(length=16), nullable=False),
    sa.Column('detected_motif', sa.String(length=48), nullable=True),
    sa.Column('taxonomy_keys', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyzed_moves_game_id'), 'analyzed_moves', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyzed_moves_game_id'), table_name='analyzed_moves')
    op.drop_table('analyzed_moves')
    op.drop_index(op.f('ix_weaknesses_user_id'), table_name='weaknesses')
    op.drop_index(op.f('ix_weaknesses_taxonomy_key'), table_name='weaknesses')
    op.drop_table('weaknesses')
    op.drop_index(op.f('ix_srs_cards_weakness_key'), table_name='srs_cards')
    op.drop_index(op.f('ix_srs_cards_user_id'), table_name='srs_cards')
    op.drop_index(op.f('ix_srs_cards_due_at'), table_name='srs_cards')
    op.drop_table('srs_cards')
    op.drop_index(op.f('ix_rating_history_user_id'), table_name='rating_history')
    op.drop_table('rating_history')
    op.drop_index(op.f('ix_puzzle_attempts_user_id'), table_name='puzzle_attempts')
    op.drop_index(op.f('ix_puzzle_attempts_puzzle_id'), table_name='puzzle_attempts')
    op.drop_table('puzzle_attempts')
    op.drop_index(op.f('ix_lessons_user_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_topic'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_games_user_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_puzzles_rating'), table_name='puzzles')
    op.drop_table('puzzles')
    # ### end Alembic commands ###
