"""puzzle kind and tolerance

Revision ID: 4989201d6296
Revises: 638502ec5703
Create Date: 2026-09-05 14:13:25.402400
"""
from alembic import op
import sqlalchemy as sa


revision = '4989201d6296'
down_revision = '638502ec5703'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzles', sa.Column('solution_san', sa.String(length=32), nullable=False, server_default=''))
    op.add_column('puzzles', sa.Column('kind', sa.String(length=16), nullable=False, server_default='tactical'))
    op.add_column('puzzles', sa.Column('tolerance_cp', sa.Integer(), nullable=False, server_default='30'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puzzles', 'tolerance_cp')
    op.drop_column('puzzles', 'kind')
    op.drop_column('puzzles', 'solution_san')
    # ### end Alembic commands ###
