"""weakness evidence weight

Revision ID: 59d9a3287e7f
Revises: 0affc85f696c
Create Date: 2026-09-05 13:10:40.959065
"""
from alembic import op
import sqlalchemy as sa


revision = '59d9a3287e7f'
down_revision = '0affc85f696c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default keeps this safe on a table that already has rows; the application
    # always supplies the value, so the default is dropped immediately afterwards.
    op.add_column(
        'weaknesses',
        sa.Column('evidence_weight', sa.Float(), nullable=False, server_default='0'),
    )
    op.alter_column('weaknesses', 'evidence_weight', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weaknesses', 'evidence_weight')
    # ### end Alembic commands ###
