"""coaching logs

Revision ID: 638502ec5703
Revises: 9f64623025d4
Create Date: 2026-09-05 13:40:33.693832
"""
from alembic import op
import sqlalchemy as sa


revision = '638502ec5703'
down_revision = '9f64623025d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
