"""store best move in uci

Revision ID: 9f64623025d4
Revises: 59d9a3287e7f
Create Date: 2026-09-05 13:34:46.603521
"""
from alembic import op
import sqlalchemy as sa


revision = '9f64623025d4'
down_revision = '59d9a3287e7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyzed_moves', sa.Column('best_move_uci', sa.String(length=8), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyzed_moves', 'best_move_uci')
    # ### end Alembic commands ###
